const resList = [
  {
    name: "Meghana Foods",
    cuisines: ["Biryani", "Andhra", "South Indian", "North Indian", "Chinese"],
    avgRating: "4.5",
    sla: {
      deliveryTime: 30,
    },
    costForTwo: "₹400 for two",
  },
  {
    name: "Biryani By Kilo",
    cuisines: [
      "Biryani",
      "Hyderabadi",
      "North Indian",
      "Kebabs",
      "Mughlai",
      "Desserts",
    ],
    avgRating: "4.1",
    deliveryTime: 34,
    costForTwo: "₹500 for two",
  },
  {
    name: "Hotel Empire",
    cuisines: ["Kebabs", "Biryani"],
    avgRating: "4.4",
    sla: {
      deliveryTime: 48,
    },
    costForTwo: "₹450 for two",
  },
  {
    name: "Sharief Bhai Biryani",
    cuisines: [
      "Biryani",
      "shawarma",
      "Kebabs",
      "Mughlai",
      "Arabian",
      "rolls",
      "Street Food",
      "Tea",
      "Desserts",
      "Beverages",
    ],
    avgRating: "3.2",
    deliveryTime: 23,
    costForTwo: "₹400 for two",
  },
  {
    name: "Anjappar",
    cuisines: [
      "Chettinad",
      "Biryani",
      "South Indian",
      "Chinese",
      "Grill",
      "Seafood",
      "North Indian",
      "Desserts",
      "Beverages",
    ],
    avgRating: "4",
    deliveryTime: 53,
    costForTwo: "₹600 for two",
  },
  {
    name: "Breeze Restaurant",
    cuisines: [
      "Chinese",
      "Kerala",
      "South Indian",
      "Hyderabadi",
      "Indian",
      "Beverages",
      "Ice Cream",
      "Juices",
      "Tandoor",
      "North Indian",
    ],
    avgRating: "4.5",
    deliveryTime: 26,
    costForTwo: "₹800 for two",
  },
  {
    name: "Nandhana Palace",
    cuisines: ["Andhra", "Biryani"],
    avgRating: "3.3",
    deliveryTime: 42,
    costForTwo: "₹500 for two",
  },
];

export default resList;